//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar_ASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auto()
        {
            this.alquiler = new HashSet<alquiler>();
        }
    
        public int idauto { get; set; }
        public string marca { get; set; }
        public string placa { get; set; }
        public string tipo { get; set; }
        public string estado { get; set; }
        public short estadoAlquiler { get; set; }
        public byte[] fotoAuto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler> alquiler { get; set; }
    }
}
